version: '3.2'
services:
    web:
        build: .
        ports:
        - "80:8080"
        volumes:
        - /mnt/logs:/var/log/nginx
      ssh:
        build: .
        ports:
        - "22:2222"
